#ANALYZING SALES PERFORMANCE

/*
  File: sales_performance.sql
  Description: This file has all the queries I wrote to understand the sales performance. It includes things like total sales by each rep, 
				which store sold the most, best product categories, and monthly sales trends.
  Author: Sushma Sharma
*/


# 1. What is the total sales amount generated by each sales representative?
SELECT sr.SalesRepID, sr.FirstName, sr.LastName, SUM(sa.TotalAmount) AS total_sales_amount 
FROM sales sa
JOIN sales_representative sr ON sa.SalesRepID = sr.SalesRepID
GROUP BY SalesRepID, FirstName, LastName;

# 2. How many products have been sold in each store location?
SELECT StoreLocation, SUM(quantity) 
FROM sales
GROUP BY StoreLocation;

# 3. Which product category has the highest total sales amount?
SELECT pr.Category, SUM(sa.TotalAmount) AS total_salesAmount 
FROM sales sa
JOIN products pr ON pr.ProductID = sa.ProductID
GROUP BY Category
ORDER BY total_salesAmount DESC
LIMIT 1;

# 4. What is the average quantity of products sold per sale?
SELECT AVG(quantity) AS avg_quantity
FROM sales;

# 5. Which customer has made the highest number of purchases?
SELECT c.CustomerID, c.FirstName, c.LastName, COUNT(SaleID) AS total_quantity 
FROM customers c
JOIN sales sa ON c.CustomerID = sa.CustomerID
GROUP BY CustomerID, FirstName, LastName
ORDER BY total_quantity DESC
LIMIT 1;

# 6. What is the distribution of total sales amounts across different months?
SELECT EXTRACT(MONTH FROM sales.Date) AS month, SUM(TotalAmount) AS total_sales 
FROM sales
GROUP BY month;

# 7. How does the sales performance of different regions compare?
SELECT sp.region, SUM(s.TotalAmount) AS total_sales
FROM sales s
JOIN sales_representative sp ON s.SalesRepID = sp.SalesRepID
GROUP BY sp.region
ORDER BY total_sales DESC;

# 8. What is the total sales amount generated for each product?
SELECT  pr.ProductName, SUM(sa.TotalAmount) AS total_amount 
FROM sales sa
JOIN products pr ON pr.ProductID = sa.ProductID
GROUP BY ProductName;

# 9. What is the average sales amount per transaction?
SELECT AVG(TotalAmount) AS avg_sales 
FROM sales;

# 10. How many sales transactions were made by each sales representative?
SELECT COUNT(*), CONCAT(sr.FirstName, ' ', sr.LastName) AS salesRepName FROM sales sa
JOIN sales_representative sr ON sa.SalesRepID = sr.SalesRepID
GROUP BY salesRepName;